In [1]:
import numpy as np

In [8]:
def naive_gauss(A, C):
    """
    param A: matrix A
    param C: matrix C
    return: matrix X
    """
    n = len(A)

    # -------------- forward elimination -------------- #
    for i in range(n):
        for j in range(i+1, n):
            m = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= m * A[i][k]
            C[j] -= m * C[i]

    X = np.zeros(n)

    # -------------- backward substitution -------------- #

    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            C[i] -= A[i][j] * X[j]
        X[i] = C[i] / A[i][i]

    return X

In [41]:
A = np.array([[25.0, 5.0, 1.0], [64.0, 8.0, 1.0], [144.0, 12.0, 1.0]])
C = np.array([106.8, 177.2, 279.2])

print("Input: ")
print("A = \n", A)
print("C = \n", C)
print()

print("Output: ")
X = naive_gauss(A, C)
print("X = \n", X)

Input: 
A = 
 [[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
C = 
 [106.8 177.2 279.2]

Output: 
X = 
 [ 0.29047619 19.69047619  1.08571429]


In [39]:
def gauss_partial_pivoting(A, C):
    """
    param A: matrix A
    param C: matrix C
    return: matrix X
    """
    n = len(A)

    # -------------- forward elimination -------------- #
    for i in range(n):
        # partial pivoting
        max_index = i
        for j in range(i+1, n):
            if abs(A[j][i]) > abs(A[max_index][i]):
                max_index = j
        A[i], A[max_index] = A[max_index].copy(), A[i].copy()
        C[i], C[max_index] = C[max_index].copy(), C[i].copy()

        for j in range(i+1, n):
            m = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] -= m * A[i][k]
            C[j] -= m * C[i]

        # print("A = \n", A)

    X = np.zeros(n)

    # -------------- backward substitution -------------- #

    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            C[i] -= A[i][j] * X[j]
        X[i] = C[i] / A[i][i]

    return X

In [42]:
A = np.array([[25.0, 5.0, 1.0], [64.0, 8.0, 1.0], [144.0, 12.0, 1.0]])
C = np.array([106.8, 177.2, 279.2])

print("Input: ")
print("A = \n", A)
print("C = \n", C)
print()

print("Output: ")
X = gauss_partial_pivoting(A, C)
print("X = \n", X)

Input: 
A = 
 [[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
C = 
 [106.8 177.2 279.2]

Output: 
X = 
 [ 0.29047619 19.69047619  1.08571429]
