In [1]:
import numpy as np

In [12]:
def LU_Decomposition(A, C):
    n = len(A)
    L = np.zeros((n, n))
    U = np.copy(A)

    for i in range(n):
        L[i][i] = 1

    # --------- LU Decomposition --------- #
    for i in range(n):
        for j in range(i+1, n):
            m = U[j][i] / U[i][i]
            L[j][i] = m
            for k in range(i, n):
                U[j][k] -= m * U[i][k]

    print("L = \n", L)
    print("U = \n", U)
    
    # --------- Forward Substitution --------- #
    Z = np.zeros((n, 1))
    for i in range(n):
        sum = 0
        for j in range(i):
            sum += L[i][j] * Z[j]
        Z[i] = C[i] - sum

    print("Z = \n", Z)
    
    # --------- Backward Substitution --------- #
    X = np.zeros((n, 1))
    for i in range(n - 1, -1, -1):
        sum = 0
        for j in range(i + 1, n):
            sum += U[i][j] * X[j]
        X[i] = (Z[i] - sum) / U[i][i]
    
    return X

In [13]:
A = np.array([[25.0, 5.0, 1.0], [64.0, 8.0, 1.0], [144.0, 12.0, 1.0]])
C = np.array([106.8, 177.2, 279.2])

print("Input: ")
print("A = \n", A)
print("C = \n", C)
print()

print("Output: ")
X = LU_Decomposition(A, C)
print("X = \n", X)

Input: 
A = 
 [[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]
C = 
 [106.8 177.2 279.2]

Output: 
L = 
 [[1.   0.   0.  ]
 [2.56 1.   0.  ]
 [5.76 3.5  1.  ]]
U = 
 [[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
Z = 
 [[106.8  ]
 [-96.208]
 [  0.76 ]]
X = 
 [[ 0.29047619]
 [19.69047619]
 [ 1.08571429]]
